### ISSUE TITLE
не могу зарегистрироваться в хаб через гугл 

### ISSUE THREAD

**Issue by Kalys01** [subutai-io/bazaar#1]
Открыл https://hub.subut.ai/register ссылку и использовал через google, так как у меня не было в facebookе и githubе.     
![image](https://user-images.githubusercontent.com/32476375/31111961-d8af9c26-a832-11e7-9466-9cd1517019d8.png)

использовал браузер Opera

**Comment by absidish** [comment]
fixed, please test

**Comment by kalys0101** [comment]
okay..
