### ISSUE TITLE
Template author should provide more info on it

### ISSUE THREAD

**Issue by efeefe** [subutai-io/bazaar#10]
### Expected behavior and actual behavior.
* Urgent: users who create and upload templates should give information on a recommended size for the container to run the application comfortably
* Other relevant info: description of application, URL of software, version, etc.

**Comment by niclash** [comment]
In general, I think we should discourage Template creations as much as possible. Instead steer people towards a few standard, high-quality templates and deploy blueprints.

**Comment by efeefe** [comment]
Agreed.
