### ISSUE TITLE
Screen faded out when "User guides" are on

### ISSUE THREAD

**Issue by efeefe** [subutai-io/bazaar#13]
Reported by @Khudairi:

When I first saw this happen on my system a few days ago (...), I thought my computer screen had suffered some sort of "sleep"/energy savings malfunction. I would recommend making this a bit brighter so a) it's easier to read, and b) it's evident that action is needed.

![bazaar - tips](https://user-images.githubusercontent.com/119052/39581247-81a290a6-4ec1-11e8-8a88-e2df41dc724f.png)

**Comment by samsonbek** [comment]
That popup dialog is removed now.
