### ISSUE TITLE
Issue tracker/repo for documentation?

### ISSUE THREAD

**Issue by mattcollier** [subutai-io/bazaar#19]
Is there someplace to track issues related to this documentation?
https://docs.subutai.io/Products/PeerOS/02_Install_PeerOS.html#install-subutai-peeros

One of the instructions state: Make sure /etc/subutai/agent.conf has the appropriate CDN URL

However, there is no mention of what an "appropriate CDN URL" is or is not.

**Comment by Shahrizada** [comment]
@mattcollier thank you very much for your issues. We will make sure to address this issues to an appropriate team.

**Comment by dilshat** [comment]
@mattcollier this step is not needed in  regular usecase
>Make sure /etc/subutai/agent.conf has the appropriate CDN URL. If not, edit and restart: systemctl restart subutai.service

Peer will have this setting auto-configured during setup. It is needed when manually moving peer between branches and used mainly by dev team

**Comment by Shahrizada** [comment]
@mattcollier and for documentation, website related issues we use this repos https://github.com/subutai-io/website or https://github.com/subutai-io/readthedocs/issues

**Comment by efeefe** [comment]
We have removed this unnecessary information from the documentation page. Thanks @mattcollier for reporting.

**Comment by mattcollier** [comment]
ty!
