### ISSUE TITLE
cant press the "slack" button on the site

### ISSUE THREAD

**Issue by Laggar93** [subutai-io/bazaar#2]
when i open the site "subutai,io", i cant press the "slack" button, because the words "conquer the cloud" stays in front of the "slack". it's a default site zoom, 100%. Chrome.

**Comment by eemilov2501** [comment]
fixed

**Comment by samsonbek** [comment]
This issue not related to Subutai Hub project, it should have been created in [subutai-io/website](https://github.com/subutai-io/website) repository.
