### ISSUE TITLE
bazaar.subutai.io requires a client certificate

### ISSUE THREAD

**Issue by core-code** [subutai-io/bazaar#21]
since yesterday i am having troubles using the official download links:

<img width="424" alt="screen shot 2018-11-01 at 18 27 37" src="https://user-images.githubusercontent.com/1261954/47868231-04689b80-de04-11e8-99d9-9580d205962c.png">

**Comment by etursunbaev** [comment]
@core-code pls check again. It is fixed.

**Comment by core-code** [comment]
@etursunbaev are you sure? i still get it in safari and chrome. could caching be responsible for the problem sticking around for me?
<img width="516" alt="screen shot 2018-11-08 at 11 46 23" src="https://user-images.githubusercontent.com/1261954/48193958-01156880-e34c-11e8-8604-24ba14f07059.png">
<img width="522" alt="screen shot 2018-11-08 at 11 46 03" src="https://user-images.githubusercontent.com/1261954/48193960-01156880-e34c-11e8-8991-f6ede6d66429.png">

**Comment by akarasulu** [comment]
I "think" it went away for me. I restarted chrome and safari. I will reboot and check again.

**Comment by etursunbaev** [comment]
@core-code can you check now
in your screenshot we found that our other domain has the same issue.
It should work now

**Comment by core-code** [comment]
i can confirm its fixed now

**Comment by etursunbaev** [comment]
@core-code Thank you very much.

**Comment by akarasulu** [comment]
Yes 100% fixed for me too. Just tried a reboot of mac in case there was some caching going on.
