### ISSUE TITLE
it's saying that I have Windows 8 when in fact I have Windows 10

### ISSUE THREAD

**Issue by qweyn** [subutai-io/bazaar#4]
![image](https://user-images.githubusercontent.com/32504128/31328730-61584e6e-acf8-11e7-83db-cae1a40f4207.png)

Dev launcher

**Comment by samsonbek** [comment]
This issue not related to Subutai Hub project, it should be reported in [subutai-io/launcher](https://github.com/subutai-io/launcher) repository.
