### ISSUE TITLE
"Subutai Launcher" does not start when there is no internet connection, I think that after the startup should notify that there is no internet connection.

### ISSUE THREAD

**Issue by qweyn** [subutai-io/bazaar#5]
![image](https://user-images.githubusercontent.com/32504128/31328793-a8248100-acf8-11e7-825f-5670cfdb5302.png)

**Comment by samsonbek** [comment]
This issue not related to Subutai Hub project, it should be reported in [subutai-io/launcher](https://github.com/subutai-io/launcher) repository.
